version: '3'

services:
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    volumes:
      - ./fe:/app
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - be
