version: '3'

services:
  db:
    image: postgres:11.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=covid
      - POSTGRES_USER=root
      - POSTGRES_DB=covid-income
    networks:
      - webnet
  be:
    command: bash -c "python manage.py migrate; python manage.py runserver 0:8000"
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    volumes:
      - ./be:/app
    ports:
      - "8000:8000"
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    networks:
      - webnet
    depends_on:
      - db

networks:
  webnet:
