# Generated by Django 3.0.4 on 2020-03-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200321_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
