# Generated by Django 3.0.4 on 2020-03-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200321_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomereport',
            name='reference_code',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
