# Generated by Django 3.0.4 on 2020-03-22 10:59

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_incomereport_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomereport',
            name='reference_code',
            field=models.CharField(default=reports.models.generate_income_report_reference_code, max_length=50, unique=True),
        ),
    ]
