# Generated by Django 3.0.4 on 2020-03-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_incomereport_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomereport',
            name='industry',
            field=models.TextField(blank=True),
        ),
    ]
