# Generated by Django 3.0.4 on 2020-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_incomereport_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomereport',
            name='cancelled_work',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='future_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='future_work_cancelled',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='monthly_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
