# Generated by Django 3.0.4 on 2020-03-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200322_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomereport',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='employed_since',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='ltd_company',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='national_insurance_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='self_employed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='incomereport',
            name='unique_tax_reference',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='incomereport',
            name='future_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='incomereport',
            name='monthly_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
