# Use the official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.8-slim

RUN apt-get update && apt-get install -y git texlive-xetex texlive-latex-base

ENV APP_HOME /app
WORKDIR $APP_HOME

ADD requirements.txt ./requirements.txt

# Install production dependencies.
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./

RUN python manage.py collectstatic --no-input

# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available.
CMD ./docker-entry.sh
