FROM python:3.8-slim

RUN apt-get update && apt-get install -y curl git texlive-xetex texlive-latex-base latexmk
RUN curl -o /usr/local/bin/watchman "https://storage.googleapis.com/static.fronted.xyz/watchman-eb16f82" -# && chmod +x /usr/local/bin/watchman

ENV APP_HOME /app
WORKDIR $APP_HOME

ADD requirements.txt ./requirements.txt

# Install dependencies.
RUN pip install --no-cache-dir -r requirements.txt
