# Generated by Django 3.0.4 on 2020-03-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creditkudosprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditkudosprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_kudos_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
