# Generated by Django 3.0.4 on 2020-03-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('users', '0004_auto_20200321_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditkudosprofile',
            name='income_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_kudos_profiles', to='reports.IncomeReport'),
        ),
    ]
